### ISSUE TITLE
Default windows size is too small 

### ISSUE THREAD

**Issue by CollinsLord** [lcabrini/jfm#10]

**Comment by lcabrini** [comment]
Yes, I am aware. It is because there on no components to render inside the window yet. When we add those components, the window will be bigger by default.

Or do you want us to make a temporary fix?

**Comment by CollinsLord** [comment]
Yes have temporary size will be fine...

**Comment by lcabrini** [comment]
+1

**Comment by CollinsLord** [comment]
okay then let me work on that.

**Comment by lcabrini** [comment]
I have merged in the change. I suggest we close.

**Comment by CollinsLord** [comment]
+1
