### ISSUE TITLE
Create space for side bar and directory contents widget

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#12]
There should be a divider that allows us to hold the sidebar to the left and the directory contents to the right. And, at least in Gnome Files this divider is movable.

**Comment by lcabrini** [comment]
It looks like we could use a JSplitPane: https://docs.oracle.com/javase/8/docs/api/javax/swing/JSplitPane.html

The Java tutorial has some info that may be useful as well: https://docs.oracle.com/javase/tutorial/uiswing/components/splitpane.html

**Comment by CollinsLord** [comment]
working on it

**Comment by lcabrini** [comment]
OK, cool.

**Comment by CollinsLord** [comment]
Do i have to label them.

**Comment by lcabrini** [comment]
Not really. Just put the splitpane there should be fine.

**Comment by lcabrini** [comment]
OK, I did a bit of cleanup of the code. You can git pull it. Can we close this issue now?

**Comment by CollinsLord** [comment]
Thanks! +1

_Sent from my TECNO-C9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
