### ISSUE TITLE
Propose we add a file directory's  to the frame.

### ISSUE THREAD

**Issue by CollinsLord** [lcabrini/jfm#13]

**Comment by lcabrini** [comment]
Can you explain a bit more in detail what you mean?

**Comment by CollinsLord** [comment]
add the directory's files . Example : Home and Document

**Comment by lcabrini** [comment]
You mean to the left sidebar? Yes, that is a good idea. But we need to build that widget first :)

**Comment by CollinsLord** [comment]
okay.

**Comment by CollinsLord** [comment]
I  sent pull request for  refs#12 and #14

_Sent from my TECNO-C9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CollinsLord** [comment]
i think you can close this issue.

**Comment by lcabrini** [comment]
OK.
