### ISSUE TITLE
Closing file manager window does not terminate program

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#14]
After the file manager window is closed the program is still running.

**Comment by CollinsLord** [comment]
working on it as well ,i should be able to push them this evening.

**Comment by lcabrini** [comment]
sure

**Comment by CollinsLord** [comment]
i hope we can close this issue

**Comment by lcabrini** [comment]
Ah, I had missed that this had been done. Didn't see a commit for it.
