### ISSUE TITLE
Create a directory reader

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#16]
We need a Java class that will read the contents of a directory and feed the directory contents widget.

**Comment by lcabrini** [comment]
This for example, may be useful: https://stackoverflow.com/questions/1844688/read-all-files-in-a-folder

**Comment by CollinsLord** [comment]
Am working on it..

**Comment by lcabrini** [comment]
Cool!

**Comment by CollinsLord** [comment]
Are you busy ....

**Comment by CollinsLord** [comment]
Are you busy ....

**Comment by lcabrini** [comment]
Can you create a pull request?

**Comment by CollinsLord** [comment]
It can been close.
