### ISSUE TITLE
LocationBar is not part of the sok.jfm.ui package

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#19]
LocationBar is placed in the ui directory so it should be part of the ui package, but it is missing the package directive.

**Comment by CollinsLord** [comment]
i think we can close some of this issues because most of the have been address.

**Comment by lcabrini** [comment]
OK, I'll close this one, because i checked. It has been resolved. I didn't know because there was no refs in the commit message I couldn't see from here. 

Can you help me to point out the other issues that can be closed?
