### ISSUE TITLE
Directory in FileReader is hard-coded

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#22]
This line:

    getList(root, new File("/home/collins/"));

Is trying to read the directory /home/collins, which does not exist on my machine.

**Comment by CollinsLord** [comment]
I think this has also been resolved from my previous pull request. But it seem you have not said anything about my last pull request.

**Comment by lcabrini** [comment]
Because I don't have back-links from here to the pull request. It makes it very difficult for me. That is why that "Refs #<number>" is so important in the commit messages. It shows me that there has been an update with regards to this issue.
