### ISSUE TITLE
Select build system

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#3]
We should select a build system. I am mostly familiar with make and especially GNU make. But it doesn't seem very popular with Java projects. Here are the ones that seem popular.

1. ant
1. maven
1. gradle
1. sbt

Not sure, but maven and gradle seem very enterprisey to me. Not really meant for a simple desktop app. SBT is perhaps more popular in the Scala community. I have used ant before. Much more complex and weird than make, but I guess it gets the job done.

**Comment by lcabrini** [comment]
I guess we verbally decided on ant. I have created a very basic build file. I guess we can close this issue.

**Comment by CollinsLord** [comment]
yes!!!!!! ant will be ok
