### ISSUE TITLE
Add javadoc comments to classes and methods

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/jfm#7]
All classes and all public methods should be properly commented.

**Comment by CollinsLord** [comment]
I believe we close this issue.. 

_Sent from my TECNO-C9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lcabrini** [comment]
Let's get the javadoc added to the App class as well first.

**Comment by lcabrini** [comment]
Now I have added javadoc comments to the App class so I am closing this issue.
